package handler

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/mheers/opencode-go-ollama-bridge/internal/adapter"
	"github.com/mheers/opencode-go-ollama-bridge/internal/client"
)

type Handler struct {
	client        *client.Client
	ollamaVersion string
	debug         bool
}

func New(c *client.Client, ollamaVersion string, debug bool) *Handler {
	return &Handler{client: c, ollamaVersion: ollamaVersion, debug: debug}
}

func (h *Handler) logf(format string, args ...interface{}) {
	if h.debug {
		log.Printf(format, args...)
	}
}

func (h *Handler) Health() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Write([]byte("Ollama is running"))
	}
}

func (h *Handler) Version() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		h.logf("[VERSION] returning version %s", h.ollamaVersion)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{
			"version": h.ollamaVersion,
		})
	}
}

func (h *Handler) Tags() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		models, err := h.client.ListModels()
		if err != nil {
			h.logf("[TAGS] failed to fetch models from OpenCode Go: %v", err)
			http.Error(w, `{"error":"failed to list models"}`, http.StatusInternalServerError)
			return
		}

		h.logf("[TAGS] fetched %d models from upstream", len(models))
		for _, m := range models {
			h.logf("[TAGS]   model: %s", m.ID)
		}

		ollamaModels := adapter.MapModelsToOllama(models)
		for _, m := range ollamaModels {
			name, _ := m["name"].(string)
			name = strings.TrimSuffix(name, ":latest")
			if details, ok := m["details"].(map[string]interface{}); ok {
				details["context_length"] = modelContextLength(name)
				details["parameter_size"] = modelParameterSize(name)
			}
		}

		resp := map[string]interface{}{
			"models": ollamaModels,
		}
		body, _ := json.Marshal(resp)
		h.logf("[TAGS] response: %s", string(body))

		w.Header().Set("Content-Type", "application/json")
		w.Write(body)
	}
}

func (h *Handler) PS() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{"models":[]}`))
	}
}

func (h *Handler) Show() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		var req struct {
			Model   string `json:"model"`
			Verbose bool   `json:"verbose"`
		}
		if err := json.Unmarshal(body, &req); err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		modelID := strings.TrimSuffix(req.Model, ":latest")

		h.logf("[SHOW] model=%s verbose=%v", modelID, req.Verbose)

		ctxLen := modelContextLength(modelID)
		paramSize := modelParameterSize(modelID)
		arch := modelArchitecture(modelID)

		resp := map[string]interface{}{
			"modelfile":  "# Generated by opencode-go-ollama-bridge\nFROM " + modelID + "\n",
			"parameters": fmt.Sprintf("num_ctx %d", ctxLen),
			"template":   "{{ .Prompt }}",
			"details": map[string]interface{}{
				"parent_model":       "",
				"format":             "gguf",
				"family":             arch,
				"families":           []string{arch},
				"parameter_size":     paramSize,
				"quantization_level": "F16",
			},
			"model_info": map[string]interface{}{
				"general.architecture":          arch,
				"general.quantization_version":   2,
				"general.file_type":              1,
				"general.context_length":         ctxLen,
				arch + ".context_length":         ctxLen,
				arch + ".block_count":            32,
			},
			"capabilities": []string{"completion", "tools"},
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func modelContextLength(modelID string) int {
	switch modelID {
	case "minimax-m2.7", "minimax-m2.5":
		return 1000000
	case "mimo-v2-pro", "mimo-v2-omni", "mimo-v2.5-pro", "mimo-v2.5":
		return 262144
	default:
		return 131072
	}
}

func modelParameterSize(modelID string) string {
	switch modelID {
	case "minimax-m2.7", "minimax-m2.5":
		return "unknown"
	case "deepseek-v4-pro":
		return "671B"
	case "deepseek-v4-flash":
		return "21B"
	case "qwen3.5-plus", "qwen3.6-plus":
		return "72B"
	case "glm-5", "glm-5.1":
		return "130B"
	case "kimi-k2.5", "kimi-k2.6":
		return "1T"
	case "mimo-v2.5", "mimo-v2.5-pro", "mimo-v2-pro", "mimo-v2-omni":
		return "unknown"
	default:
		return "unknown"
	}
}

func modelArchitecture(modelID string) string {
	switch {
	case strings.HasPrefix(modelID, "deepseek"):
		return "deepseek2"
	case strings.HasPrefix(modelID, "qwen"):
		return "qwen2"
	case strings.HasPrefix(modelID, "glm"):
		return "glm"
	case strings.HasPrefix(modelID, "kimi"):
		return "kimi"
	case strings.HasPrefix(modelID, "minimax"):
		return "minimax"
	case strings.HasPrefix(modelID, "mimo"):
		return "mimo"
	default:
		return modelID
	}
}

func (h *Handler) V1ChatCompletions() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, `{"error":"bad request"}`, http.StatusBadRequest)
			return
		}

		var req struct {
			Model       string          `json:"model"`
			Messages    json.RawMessage `json:"messages"`
			Stream      bool            `json:"stream"`
			Tools       json.RawMessage `json:"tools"`
			Temperature *float64        `json:"temperature"`
			MaxTokens   *int            `json:"max_tokens"`
		}
		if err := json.Unmarshal(body, &req); err != nil {
			h.logf("[V1/CHAT] parse error: %v", err)
			http.Error(w, `{"error":"bad request"}`, http.StatusBadRequest)
			return
		}

		modelID := strings.TrimSuffix(req.Model, ":latest")

		h.logf("[V1/CHAT] model=%s stream=%v body_has_reasoning=%v", modelID, req.Stream, strings.Contains(string(body), "reasoning_content"))

		var upstreamResp *http.Response
		var upstreamErr error

		if adapter.IsMiniMaxModel(modelID) {
			h.logf("[V1/CHAT] routing to anthropic backend for %s", modelID)
			anthReq := map[string]interface{}{
				"model":      modelID,
				"max_tokens": 65536,
				"messages":   json.RawMessage(req.Messages),
				"stream":     req.Stream,
			}
			if req.Temperature != nil {
				anthReq["temperature"] = *req.Temperature
			}
			if req.Tools != nil {
				var tools []adapter.AnthropicTool
				h.convertOAToolsToAnthropic(req.Tools, &tools)
				if len(tools) > 0 {
					anthReq["tools"] = tools
				}
			}
			upstreamResp, upstreamErr = h.client.Messages(anthReq)
		} else {
			h.logf("[V1/CHAT] routing to openai backend for %s", modelID)
			var proxyReq map[string]interface{}
			if err := json.Unmarshal(body, &proxyReq); err != nil {
				http.Error(w, `{"error":"bad request"}`, http.StatusBadRequest)
				return
			}
			proxyReq["model"] = modelID
			h.fixDeepSeekMessages(proxyReq)
			upstreamResp, upstreamErr = h.client.ChatCompletions(proxyReq)
		}

		if upstreamErr != nil {
			h.logf("[V1/CHAT] upstream error: %v", upstreamErr)
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadGateway)
			json.NewEncoder(w).Encode(map[string]interface{}{
				"error": map[string]interface{}{
					"message": fmt.Sprintf("upstream request failed: %v", upstreamErr),
					"type":    "upstream_error",
				},
			})
			return
		}
		defer upstreamResp.Body.Close()

		if upstreamResp.StatusCode >= 400 {
			body, _ := io.ReadAll(io.LimitReader(upstreamResp.Body, 16384))
			h.logf("[V1/CHAT] upstream error status %d: %s", upstreamResp.StatusCode, string(body))
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(upstreamResp.StatusCode)
			w.Write(body)
			return
		}

		copyHeader := upstreamResp.Header.Get("Content-Type")
		if copyHeader != "" {
			w.Header().Set("Content-Type", copyHeader)
		} else {
			w.Header().Set("Content-Type", "application/json")
		}

		if req.Stream {
			flusher, ok := w.(http.Flusher)
			if !ok {
				h.logf("[V1/CHAT] streaming not supported by http.ResponseWriter")
				http.Error(w, `{"error":"streaming not supported"}`, http.StatusInternalServerError)
				return
			}
			w.WriteHeader(http.StatusOK)
			buf := make([]byte, 4096)
			for {
				n, err := upstreamResp.Body.Read(buf)
				if n > 0 {
					if _, werr := w.Write(buf[:n]); werr != nil {
						h.logf("[V1/CHAT] write error: %v", werr)
						return
					}
					flusher.Flush()
				}
				if err != nil {
					if err != io.EOF {
						h.logf("[V1/CHAT] stream read error: %v", err)
					}
					break
				}
			}
			return
		}

		w.WriteHeader(upstreamResp.StatusCode)
		io.Copy(w, upstreamResp.Body)
	}
}

func (h *Handler) convertOAToolsToAnthropic(toolsRaw json.RawMessage, out *[]adapter.AnthropicTool) {
	var tools []struct {
		Type     string `json:"type"`
		Function struct {
			Name        string          `json:"name"`
			Description string          `json:"description"`
			Parameters  json.RawMessage `json:"parameters"`
		} `json:"function"`
	}
	if err := json.Unmarshal(toolsRaw, &tools); err != nil {
		return
	}
	for _, t := range tools {
		*out = append(*out, adapter.AnthropicTool{
			Name:        t.Function.Name,
			Description: t.Function.Description,
			InputSchema: t.Function.Parameters,
		})
	}
}

func (h *Handler) V1Models() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		models, err := h.client.ListModels()
		if err != nil {
			h.logf("[V1/MODELS] failed: %v", err)
			http.Error(w, `{"error":"failed to list models"}`, http.StatusInternalServerError)
			return
		}

		data := make([]map[string]interface{}, 0, len(models))
		for _, m := range models {
			data = append(data, map[string]interface{}{
				"id":             m.ID,
				"object":         "model",
				"created":        0,
				"owned_by":       "opencode-go",
				"context_length": modelContextLength(m.ID),
				"max_tokens":     modelContextLength(m.ID),
			})
		}

		h.logf("[V1/MODELS] returning %d models", len(data))

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{
			"object": "list",
			"data":   data,
		})
	}
}

func injectEmptyReasoningContent(req map[string]interface{}) {
	msgs, ok := req["messages"].([]interface{})
	if !ok {
		return
	}
	for _, m := range msgs {
		msg, ok := m.(map[string]interface{})
		if !ok {
			continue
		}
		if role, _ := msg["role"].(string); role == "assistant" {
			if _, exists := msg["reasoning_content"]; !exists {
				msg["reasoning_content"] = ""
			}
		}
	}
}

func (h *Handler) fixDeepSeekMessages(req map[string]interface{}) {
	msgs, ok := req["messages"].([]interface{})
	if !ok {
		return
	}

	h.logf("[FIX] scanning %d messages", len(msgs))
	for i, m := range msgs {
		msg, ok := m.(map[string]interface{})
		if !ok {
			continue
		}
		role, _ := msg["role"].(string)
		_, hasTC := msg["tool_calls"]
		h.logf("[FIX]   [%d] role=%s has_tool_calls=%v", i, role, hasTC)
	}

	fixed := make([]interface{}, 0, len(msgs))

	for i, m := range msgs {
		msg, ok := m.(map[string]interface{})
		if !ok {
			fixed = append(fixed, m)
			continue
		}

		role, _ := msg["role"].(string)

		if role == "assistant" {
			if _, exists := msg["reasoning_content"]; !exists {
				msg["reasoning_content"] = ""
			}
		}

		if role == "assistant" && msg["tool_calls"] != nil {
			hasToolResponses := false
			for j := i + 1; j < len(msgs); j++ {
				next, ok := msgs[j].(map[string]interface{})
				if !ok {
					continue
				}
				nextRole, _ := next["role"].(string)
				if nextRole == "tool" {
					hasToolResponses = true
				}
				if nextRole != "tool" {
					break
				}
			}
			if !hasToolResponses {
				h.logf("[FIX] removing orphaned tool_calls from assistant[%d]", i)
				delete(msg, "tool_calls")
			} else {
				h.logf("[FIX] keeping tool_calls on assistant[%d] (followed by tool messages)", i)
			}
		}

		if role == "tool" {
			toolCallID, _ := msg["tool_call_id"].(string)
			hasPreceding := false
			for k := i - 1; k >= 0; k-- {
				prev, ok := msgs[k].(map[string]interface{})
				if !ok {
					continue
				}
				prevRole, _ := prev["role"].(string)
				if prevRole == "tool" {
					continue
				}
				if prevRole == "assistant" {
					toolCalls, _ := prev["tool_calls"].([]interface{})
					for _, tc := range toolCalls {
						tcm, _ := tc.(map[string]interface{})
						if tid, _ := tcm["id"].(string); tid == toolCallID {
							hasPreceding = true
							break
						}
					}
				}
				break
			}
			if !hasPreceding {
				h.logf("[FIX] dropping orphaned tool message[%d]", i)
				continue
			}
		}

		fixed = append(fixed, m)
	}

	req["messages"] = fixed

	h.logf("[FIX] result: %d messages", len(fixed))
	for i, m := range fixed {
		if msg, ok := m.(map[string]interface{}); ok {
			role, _ := msg["role"].(string)
			_, hasTC := msg["tool_calls"]
			h.logf("[FIX]   [%d] role=%s has_tool_calls=%v", i, role, hasTC)
		}
	}
}

func (h *Handler) Chat() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		var ollamaReq adapter.OllamaChatRequest
		if err := json.Unmarshal(body, &ollamaReq); err != nil {
			h.logf("[CHAT] parse error: %v | body: %s", err, string(body))
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		h.logf("[CHAT] model=%s stream=%v messages=%d tools=%d",
			ollamaReq.Model, boolPtr(ollamaReq.Stream), len(ollamaReq.Messages), len(ollamaReq.Tools))

		if adapter.IsMiniMaxModel(ollamaReq.Model) {
			h.logf("[CHAT] routing to anthropic backend for %s", ollamaReq.Model)
			h.handleChatAnthropic(w, &ollamaReq)
			return
		}

		h.logf("[CHAT] routing to openai backend for %s", ollamaReq.Model)
		h.handleChatOpenAI(w, &ollamaReq)
	}
}

func (h *Handler) handleChatOpenAI(w http.ResponseWriter, ollamaReq *adapter.OllamaChatRequest) {
	openaiReq := adapter.ChatRequestToOpenAI(ollamaReq)

	resp, err := h.client.ChatCompletions(openaiReq)
	if err != nil {
		h.logf("[CHAT] upstream error (openai): %v", err)
		http.Error(w, `{"error":"upstream request failed"}`, http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		h.logf("[CHAT] upstream error status %d: %s", resp.StatusCode, string(body))
		http.Error(w, string(body), resp.StatusCode)
		return
	}

	if openaiReq.Stream {
		w.Header().Set("Content-Type", "application/x-ndjson")
		w.WriteHeader(http.StatusOK)
		flusher, ok := w.(http.Flusher)
		if !ok {
			http.Error(w, "streaming not supported", http.StatusInternalServerError)
			return
		}

		if err := adapter.OpenAIStreamToOllamaNDJSON(resp.Body, ollamaReq.Model, w); err != nil {
			h.logf("[CHAT] stream error: %v", err)
			return
		}
		flusher.Flush()
		return
	}

	var openaiResp adapter.OpenAIResponse
	if err := json.NewDecoder(resp.Body).Decode(&openaiResp); err != nil {
		h.logf("[CHAT] decode error: %v", err)
		http.Error(w, `{"error":"failed to decode response"}`, http.StatusInternalServerError)
		return
	}

	ollamaResp := adapter.OpenAIResponseToOllamaChat(&openaiResp, ollamaReq.Model)
	h.logf("[CHAT] response: done=%v content_len=%d", ollamaResp.Done, len(ollamaResp.Message.Content))

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(ollamaResp)
}

func (h *Handler) handleChatAnthropic(w http.ResponseWriter, ollamaReq *adapter.OllamaChatRequest) {
	anthReq := adapter.ChatRequestToAnthropic(ollamaReq)

	var resp *http.Response
	var err error
	resp, err = h.client.Messages(anthReq)
	if err != nil {
		h.logf("[CHAT] upstream error (anthropic): %v", err)
		http.Error(w, `{"error":"upstream request failed"}`, http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		h.logf("[CHAT] upstream error status %d: %s", resp.StatusCode, string(body))
		http.Error(w, string(body), resp.StatusCode)
		return
	}

	if anthReq.Stream {
		w.Header().Set("Content-Type", "application/x-ndjson")
		w.WriteHeader(http.StatusOK)
		flusher, ok := w.(http.Flusher)
		if !ok {
			http.Error(w, "streaming not supported", http.StatusInternalServerError)
			return
		}

		if err := adapter.AnthropicStreamToOllamaNDJSON(resp.Body, ollamaReq.Model, w); err != nil {
			h.logf("[CHAT] stream error: %v", err)
			return
		}
		flusher.Flush()
		return
	}

	http.Error(w, `{"error":"non-streaming anthropic not yet supported"}`, http.StatusNotImplemented)
}

func (h *Handler) Generate() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		body, err := io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		var genReq adapter.OllamaGenerateRequest
		if err := json.Unmarshal(body, &genReq); err != nil {
			h.logf("[GENERATE] parse error: %v | body: %s", err, string(body))
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}

		h.logf("[GENERATE] model=%s stream=%v prompt_len=%d",
			genReq.Model, boolPtr(genReq.Stream), len(genReq.Prompt))

		openaiReq := adapter.GenerateRequestToOpenAI(&genReq)

		resp, err := h.client.ChatCompletions(openaiReq)
		if err != nil {
			h.logf("[GENERATE] upstream error: %v", err)
			http.Error(w, `{"error":"upstream request failed"}`, http.StatusBadGateway)
			return
		}
		defer resp.Body.Close()

		if resp.StatusCode >= 400 {
			body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
			h.logf("[GENERATE] upstream error status %d: %s", resp.StatusCode, string(body))
			http.Error(w, string(body), resp.StatusCode)
			return
		}

		if openaiReq.Stream {
			w.Header().Set("Content-Type", "application/x-ndjson")
			w.WriteHeader(http.StatusOK)
			flusher, ok := w.(http.Flusher)
			if !ok {
				http.Error(w, "streaming not supported", http.StatusInternalServerError)
				return
			}

			if err := adapter.OpenAIStreamToOllamaNDJSON(resp.Body, genReq.Model, w); err != nil {
				h.logf("[GENERATE] stream error: %v", err)
				return
			}
			flusher.Flush()
			return
		}

		var openaiResp adapter.OpenAIResponse
		if err := json.NewDecoder(resp.Body).Decode(&openaiResp); err != nil {
			h.logf("[GENERATE] decode error: %v", err)
			http.Error(w, `{"error":"failed to decode response"}`, http.StatusInternalServerError)
			return
		}

		ollamaResp := adapter.OpenAIResponseToOllamaChat(&openaiResp, genReq.Model)

		if len(ollamaResp.DoneReason) == 0 && ollamaResp.Done {
			ollamaResp.DoneReason = "stop"
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(ollamaResp)
	}
}

func boolPtr(b *bool) bool {
	if b == nil {
		return false
	}
	return *b
}


